language: go

go:
<<<<<<< HEAD
  - 1.11.x
=======
  - master
>>>>>>> f33c3a477711033e1c5c5c04e72ce2c3c83f449e

# whitelist
branches:
  only:
  - master
  - stable

script:
  - go get -t -v ./...
  - go vet ./...
  - bash ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)